#!/bin/sh

DIRECTORIES=(
    /home/$USER/Pictures
    /home/$USER/Desktop
    /home/$USER/Templates
    /home/$USER/python_games
    /home/$USER/Documents
    /home/$USER/Documents
    /home/$USER/Music)

for dir in $DIRECTORIES; do mkdir -p $dir; done

wget https://raw.githubusercontent.com/mrbensoncyber1/Piscavengerhunt/refs/heads/main/Sekol.txt -P "/home/$USER/Pictures"
wget https://raw.githubusercontent.com/mrbensoncyber1/Piscavengerhunt/refs/heads/main/Benson.txt -P "/home/$USER/Desktop"
wget https://raw.githubusercontent.com/mrbensoncyber1/Piscavengerhunt/refs/heads/main/Bionci.txt -P "/home/$USER/Templates"
wget https://raw.githubusercontent.com/mrbensoncyber1/Piscavengerhunt/refs/heads/main/Miller.txt -P "/home/$USER/python_games"
wget https://raw.githubusercontent.com/mrbensoncyber1/Piscavengerhunt/refs/heads/main/Mabel.txt -P "/home/$USER/Documents"
wget https://raw.githubusercontent.com/mrbensoncyber1/Piscavengerhunt/refs/heads/main/Ch3ster.txt -P "/home/$USER/Documents"
wget https://raw.githubusercontent.com/mrbensoncyber1/Piscavengerhunt/refs/heads/main/Fozzie.txt -P "/home/$USER/Music"
